{{- if .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certManager.issuerName }}
spec:
  acme:
    email: {{ .Values.certManager.email | quote }}
    server: {{ .Values.certManager.server | quote }}
    privateKeySecretRef:
      name: {{ printf "%s-private-key" .Values.certManager.issuerName | quote }}
    solvers:
      - http01:
          ingress:
            class: {{ .Values.certManager.solverClass | quote }}
{{- end }}
