replicaCount: 1

imagePullSecrets:
  - name: dockerhub-cred

deployment:
  namespace: mroh
  
app:
  name: frontend
  image:
    repository: iamqsoh/mroh-frontend
    tag: latest
    pullPolicy: Always
  port: 3000
  env:
    NEXT_PUBLIC_API_BASE: https://mroh.me/api

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  host: mroh.me
  path: /
  pathType: Prefix
  annotations: {}
  managedCertificate:
    enabled: false
    name: frontend-managed-cert
  staticIpName: ""
  tls:
    enabled: true
    secretName: frontend-tls
  api:
    enabled: true
    path: /api
    serviceName: data-service
    servicePort: 80

certManager:
  enabled: true
  issuerName: frontend-letsencrypt
  email: iam.qsoh@gmail.com
  server: https://acme-v02.api.letsencrypt.org/directory
  solverClass: nginx
