replicaCount: 1

app:
  name: frontend
  image:
    repository: REPLACE_ME
    tag: latest
    pullPolicy: IfNotPresent
  port: 3000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: gce
  host: app.example.com
  path: /
  pathType: Prefix
